version: "3.7"

services:
  tanp-php-prod:
    image: tanp-php-prod
    container_name: tanp-php-prod
    build:
      context: .
      dockerfile: Dockerfile.php
    networks:
      - tanp-prod

  tanp-nginx-prod:
    image: tanp-nginx-prod
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: tanp-nginx-prod
    ports:
      - 80:80
    depends_on:
      - tanp-php-prod
    networks:
      - tanp-prod
  tanp-db:
    image: mysql:5.7
    container_name: tanp-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - tanp_mysql_prod_volume:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - tanp-prod
networks:
  tanp-prod:
    driver: bridge
volumes:
  tanp_mysql_prod_volume:
    driver: local
