version: "3.7"

services:
  tanp-php-prod:
    image: 016992890397.dkr.ecr.ap-northeast-1.amazonaws.com/tanp-php-prod:1.0.7
    container_name: tanp-php-prod
    build:
      context: .
      dockerfile: Dockerfile.php
    networks:
      - tanp-prod

  tanp-nginx-prod:
    image: 016992890397.dkr.ecr.ap-northeast-1.amazonaws.com/tanp-nginx-prod:1.0.4
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: tanp-nginx-prod
    ports:
      - 80:80
    depends_on:
      - tanp-php-prod
    networks:
      - tanp-prod
networks:
  tanp-prod:
    driver: bridge
